// Updated 2026-10-04: the 10/3 MTT added from the Hammerhead event export.
// Season points from 5 events (3 tournaments + 9/19 and 9/26 SNGs).
// delta = rank change since the 9/26/26 update (null = new to the board).
// gained = GTokens earned in the 10/3 MTT (40 GTo per entry, top 7 of 44 entries).

export type Standing = { rank: number; name: string; netid: string; events: number; points: number; delta: number | null; gained: number };

export const standings: Standing[] = [
  { rank: 1, name: "Ivaylo Maksimov", netid: "imaks2", events: 4, points: 1049, delta: 0, gained: 0 },
  { rank: 2, name: "Kain Nakai", netid: "knakai2", events: 4, points: 827, delta: 0, gained: 0 },
  { rank: 3, name: "Ish Patel", netid: "ipate22", events: 5, points: 588, delta: 7, gained: 252 },
  { rank: 4, name: "Andre Ruiz Loera", netid: "andrer3", events: 3, points: 587, delta: 76, gained: 587 },
  { rank: 5, name: "Max Uvarov", netid: "muvaro2", events: 5, points: 495, delta: 1, gained: 92 },
  { rank: 6, name: "Arjun Srivastava", netid: "arjuns9", events: 2, points: 436, delta: -3, gained: 0 },
  { rank: 7, name: "Daniel Zajac", netid: "dzaja", events: 4, points: 424, delta: 56, gained: 378 },
  { rank: 8, name: "Dylan Tan", netid: "dylankt2", events: 3, points: 414, delta: -4, gained: 0 },
  { rank: 9, name: "Vidur Jannapureddy", netid: "vrj2", events: 2, points: 412, delta: -4, gained: 0 },
  { rank: 10, name: "Eric", netid: "erics11", events: 5, points: 392, delta: 14, gained: 115 },
  { rank: 11, name: "Phillip Zhao", netid: "pz15", events: 4, points: 348, delta: -4, gained: 0 },
  { rank: 12, name: "Abhi Kotari", netid: "akotari2", events: 4, points: 344, delta: -4, gained: 0 },
  { rank: 13, name: "Arnav Sirigere", netid: "arnavss3", events: 5, points: 336, delta: -4, gained: 0 },
  { rank: 14, name: "Saavan Kiran", netid: "saavank2", events: 4, points: 336, delta: -3, gained: 0 },
  { rank: 15, name: "Brayden Andersen", netid: "bande91", events: 5, points: 327, delta: -3, gained: 0 },
  { rank: 16, name: "David Sun", netid: "davids27", events: 5, points: 312, delta: -3, gained: 0 },
  { rank: 17, name: "Luca Tricarico", netid: "ltric", events: 3, points: 299, delta: -3, gained: 0 },
  { rank: 18, name: "Nick Baldev", netid: "nbaldev2", events: 2, points: 290, delta: -3, gained: 0 },
  { rank: 19, name: "Advait Gaur", netid: "advaitg2", events: 3, points: 288, delta: -3, gained: 0 },
  { rank: 20, name: "Brian Tay", netid: "bctay2", events: 4, points: 288, delta: -3, gained: 0 },
  { rank: 21, name: "Isaac Bacchus", netid: "ibacch2", events: 4, points: 288, delta: -3, gained: 0 },
  { rank: 22, name: "ishaans6", netid: "ishaans6", events: 3, points: 288, delta: -3, gained: 0 },
  { rank: 23, name: "Jin Zhang", netid: "jin61", events: 4, points: 288, delta: -3, gained: 0 },
  { rank: 24, name: "rishils3", netid: "rishils3", events: 2, points: 288, delta: -3, gained: 0 },
  { rank: 25, name: "Seungmin Cho", netid: "sc84", events: 3, points: 288, delta: -3, gained: 0 },
  { rank: 26, name: "Steven Piotrowski", netid: "stevenp8", events: 2, points: 288, delta: -3, gained: 0 },
  { rank: 27, name: "Gavin", netid: "zw53", events: 3, points: 231, delta: 38, gained: 189 },
  { rank: 28, name: "Ian lai", netid: "ianlai2", events: 3, points: 226, delta: -3, gained: 0 },
  { rank: 29, name: "Ian McGinness", netid: "ianrm", events: 3, points: 208, delta: -3, gained: 0 },
  { rank: 30, name: "Baiyan Cai", netid: "bcai", events: 5, points: 187, delta: -3, gained: 0 },
  { rank: 31, name: "James Dai", netid: "jamesd12", events: 5, points: 186, delta: -3, gained: 0 },
  { rank: 32, name: "Rishi Bhavsar", netid: "rishimb2", events: 4, points: 184, delta: -3, gained: 0 },
  { rank: 33, name: "Jonathan", netid: "zhong43", events: 1, points: 158, delta: -3, gained: 0 },
  { rank: 34, name: "Jonathan (Zhi Yong) Tan", netid: "jztan3", events: 3, points: 147, delta: 82, gained: 147 },
  { rank: 35, name: "Mihir Malik", netid: "mihirm3", events: 3, points: 144, delta: -4, gained: 0 },
  { rank: 36, name: "Wyatt Sturn", netid: "wsturn2", events: 5, points: 144, delta: -4, gained: 0 },
  { rank: 37, name: "Dharahaas Nalla", netid: "drnalla2", events: 5, points: 142, delta: -4, gained: 0 },
  { rank: 38, name: "Matthew Hannemann", netid: "mjhan", events: 1, points: 123, delta: -4, gained: 0 },
  { rank: 39, name: "Andrew Cheng", netid: "ac158", events: 2, points: 120, delta: -4, gained: 0 },
  { rank: 40, name: "Barry", netid: "zihangz3", events: 3, points: 120, delta: -4, gained: 0 },
  { rank: 41, name: "Ebk", netid: "ebk", events: 1, points: 120, delta: -4, gained: 0 },
  { rank: 42, name: "Jacky(Junqi) Xu", netid: "jackyxu2", events: 3, points: 120, delta: -4, gained: 0 },
  { rank: 43, name: "kcavyan2", netid: "kcavyan2", events: 1, points: 120, delta: -4, gained: 0 },
  { rank: 44, name: "Nick Trapp", netid: "ndtrapp2", events: 2, points: 120, delta: -4, gained: 0 },
  { rank: 45, name: "Pranav Chawla", netid: "pchawla4", events: 4, points: 120, delta: -4, gained: 0 },
  { rank: 46, name: "Sams9", netid: "sams9", events: 1, points: 120, delta: -4, gained: 0 },
  { rank: 47, name: "Grant Zhao", netid: "grantz2", events: 3, points: 105, delta: -4, gained: 0 },
  { rank: 48, name: "Aaron Wu", netid: "aaronwu2", events: 5, points: 101, delta: -4, gained: 0 },
  { rank: 49, name: "Nikhil Lalwani", netid: "nikhill2", events: 1, points: 101, delta: -4, gained: 0 },
  { rank: 50, name: "Brandon Regalado", netid: "bor3", events: 3, points: 100, delta: -4, gained: 0 },
  { rank: 51, name: "emeco3", netid: "emeco3", events: 2, points: 96, delta: -4, gained: 0 },
  { rank: 52, name: "Nikunj Mall", netid: "nikunjm2", events: 4, points: 96, delta: -4, gained: 0 },
  { rank: 53, name: "Raymond Yang", netid: "ry25", events: 1, points: 96, delta: -4, gained: 0 },
  { rank: 54, name: "Tejas Raghuram", netid: "tejasr5", events: 5, points: 96, delta: -4, gained: 0 },
  { rank: 55, name: "Harry Yao", netid: "harryy4", events: 2, points: 75, delta: -4, gained: 0 },
  { rank: 56, name: "Ruhaan Dev", netid: "rdev2", events: 2, points: 73, delta: -4, gained: 0 },
  { rank: 57, name: "Andrew Kwon", netid: "ak173", events: 4, points: 72, delta: -4, gained: 0 },
  { rank: 58, name: "Ashton Weiss", netid: "ajweis", events: 1, points: 69, delta: -4, gained: 0 },
  { rank: 59, name: "shushi meng", netid: "shushim2", events: 2, points: 61, delta: -4, gained: 0 },
  { rank: 60, name: "Sanjit Kumar", netid: "sanjit3", events: 2, points: 57, delta: -4, gained: 0 },
  { rank: 61, name: "Vincent You", netid: "vtyou2", events: 1, points: 52, delta: -4, gained: 0 },
  { rank: 62, name: "dtdang2", netid: "dtdang2", events: 1, points: 48, delta: -4, gained: 0 },
  { rank: 63, name: "Henry Chen", netid: "hechen", events: 4, points: 48, delta: -4, gained: 0 },
  { rank: 64, name: "Nav", netid: "hnn5", events: 4, points: 48, delta: -4, gained: 0 },
  { rank: 65, name: "Simon Yin", netid: "simony3", events: 1, points: 48, delta: -4, gained: 0 },
  { rank: 66, name: "Victor Li", netid: "wentaol4", events: 2, points: 48, delta: -4, gained: 0 },
  { rank: 67, name: "Edward Jiang", netid: "ejiang6", events: 2, points: 45, delta: -3, gained: 0 },
  { rank: 68, name: "Luoxiang Pan", netid: "lp29", events: 1, points: 36, delta: -2, gained: 0 },
  { rank: 69, name: "Tyler Schultz", netid: "tylerbs3", events: 1, points: 34, delta: -2, gained: 0 },
  { rank: 70, name: "Harish Chen", netid: "harish6", events: 2, points: 24, delta: -2, gained: 0 },
  { rank: 71, name: "Jett Jacobus", netid: "jettgj2", events: 3, points: 24, delta: -2, gained: 0 },
  { rank: 72, name: "Joseph Wenzke", netid: "jwenzke2", events: 2, points: 24, delta: -2, gained: 0 },
  { rank: 73, name: "Matthew Chang", netid: "mtchang2", events: 4, points: 24, delta: -2, gained: 0 },
  { rank: 74, name: "Patrick", netid: "posmith2", events: 3, points: 24, delta: -2, gained: 0 },
  { rank: 75, name: "Paul Federico", netid: "pkfede", events: 2, points: 24, delta: -2, gained: 0 },
  { rank: 76, name: "skyada2", netid: "skyada2", events: 1, points: 24, delta: -2, gained: 0 },
  { rank: 77, name: "Wei Yuan Chen", netid: "wychen3", events: 5, points: 24, delta: -2, gained: 0 },
  { rank: 78, name: "aahme121", netid: "aahme121", events: 1, points: 0, delta: null, gained: 0 },
  { rank: 79, name: "Aaron Son", netid: "ason5", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 80, name: "Aaron Zawislak", netid: "aaronsz2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 81, name: "Adi Jha", netid: "adijha2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 82, name: "Aiden Ye", netid: "aidenye2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 83, name: "amyyl2", netid: "amyyl2", events: 1, points: 0, delta: null, gained: 0 },
  { rank: 84, name: "Andrew Sherman", netid: "aps19", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 85, name: "Arnav Das", netid: "anarvtd2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 86, name: "Aryan Gupta", netid: "aryang11", events: 3, points: 0, delta: -3, gained: 0 },
  { rank: 87, name: "Austin Hickey", netid: "austinh8", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 88, name: "Austin Park", netid: "apark84", events: 4, points: 0, delta: -3, gained: 0 },
  { rank: 89, name: "Bratindra", netid: "bthati2", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 90, name: "Chinmay Raghvendran", netid: "cr64", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 91, name: "Danny Jiang", netid: "dannyj2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 92, name: "Devin Jiang", netid: "devinj2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 93, name: "Dylan", netid: "xzeng30", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 94, name: "Edwin Lu", netid: "elu29", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 95, name: "Edwin Stoiber", netid: "edwinws2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 96, name: "Edwin Thompson", netid: "ejthom", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 97, name: "Eishit Toshniwal", netid: "et25", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 98, name: "Emmanuel Zhang", netid: "ez9", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 99, name: "Eric Feng", netid: "ericf6", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 100, name: "Ethan Shen", netid: "eshen9", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 101, name: "Ethan Song", netid: "ethans15", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 102, name: "Faris Kakkodi", netid: "kakkodi2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 103, name: "Gianna Ortega", netid: "giannao2", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 104, name: "Harrison", netid: "hhe19", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 105, name: "Harsha Tumu", netid: "htumu2", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 106, name: "Harsheet Bansal", netid: "hbansal4", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 107, name: "Hein Maung", netid: "heinm2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 108, name: "Ibrahim Kamran", netid: "ikamr2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 109, name: "Ivy Shi", netid: "ivyshi2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 110, name: "Jack Newark", netid: "jnewark2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 111, name: "Jacob Kaufman", netid: "jacobtk5", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 112, name: "James Smith", netid: "jamesrs5", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 113, name: "james40", netid: "james40", events: 1, points: 0, delta: null, gained: 0 },
  { rank: 114, name: "Jay Patel", netid: "jaykp2", events: 1, points: 0, delta: -4, gained: 0 },
  { rank: 115, name: "Jaydin", netid: "jaydinr2", events: 1, points: 0, delta: -4, gained: 0 },
  { rank: 116, name: "Jeffrey Park", netid: "minjaep3", events: 1, points: 0, delta: -4, gained: 0 },
  { rank: 117, name: "Jiadong Yang", netid: "jiadong9", events: 1, points: 0, delta: -4, gained: 0 },
  { rank: 118, name: "Jonah O’Neill", netid: "jonahco2", events: 2, points: 0, delta: -4, gained: 0 },
  { rank: 119, name: "Jonas", netid: "jonasrg2", events: 1, points: 0, delta: -4, gained: 0 },
  { rank: 120, name: "Jonathan Lou", netid: "jlou12", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 121, name: "June", netid: "juneahn2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 122, name: "Justin Angres", netid: "jangres2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 123, name: "Kabir Mahatme", netid: "kabirm5", events: 3, points: 0, delta: -3, gained: 0 },
  { rank: 124, name: "Kai Karadi", netid: "kaick2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 125, name: "Kartikey Sharma", netid: "ks129", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 126, name: "Keshav Ramamurthy", netid: "keshav4", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 127, name: "Kevin Yang", netid: "keviny13", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 128, name: "Khoi", netid: "khoihn2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 129, name: "Leo Yeh", netid: "yeh21", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 130, name: "Liwei Zheng", netid: "liweiz3", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 131, name: "LLoyd Feng", netid: "lloydf3", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 132, name: "Logan McCarthy", netid: "logandm2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 133, name: "Matteo Wilkinson", netid: "matteow2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 134, name: "Maulik Bansal", netid: "maulikb2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 135, name: "Mihika Samavedam", netid: "mihika3", events: 3, points: 0, delta: -3, gained: 0 },
  { rank: 136, name: "Moksh Desai", netid: "mokshd2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 137, name: "Nate Andolina", netid: "natea2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 138, name: "Nate Leonauskas", netid: "natel4", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 139, name: "Neev patel", netid: "neev2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 140, name: "Neil Yuanting Li", netid: "neilli2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 141, name: "Nikhil Padarthy", netid: "nyp2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 142, name: "Peter Phan", netid: "huytp2", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 143, name: "Rahul Agrawal", netid: "ra47", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 144, name: "Raju Arisetty", netid: "rajua2", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 145, name: "ramnath4", netid: "ramnath4", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 146, name: "Riley Gu", netid: "rileygu2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 147, name: "Rino Lim", netid: "rlim24", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 148, name: "Rohin Patel", netid: "rohinap2", events: 3, points: 0, delta: -3, gained: 0 },
  { rank: 149, name: "Sam Sathiaraj", netid: "ss196", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 150, name: "Samuel Chen", netid: "samuel81", events: 3, points: 0, delta: -3, gained: 0 },
  { rank: 151, name: "Satyam Puniya", netid: "spuniya2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 152, name: "Seth Solovy", netid: "ssolovy2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 153, name: "Sharan Metha", netid: "sharanm2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 154, name: "Shaurya Khemka", netid: "skhemka3", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 155, name: "Shiven Gupta", netid: "shiven3", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 156, name: "Shriteja Patil", netid: "spati72", events: 3, points: 0, delta: -3, gained: 0 },
  { rank: 157, name: "Sumanohar Mulagala", netid: "sm189", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 158, name: "Surya Sridharan", netid: "surya6", events: 2, points: 0, delta: -3, gained: 0 },
  { rank: 159, name: "Tarun Srinivas", netid: "taruns5", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 160, name: "teja koripella", netid: "tejavk2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 161, name: "Terry Qiu", netid: "terryq2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 162, name: "Varshith Satti", netid: "vsatti2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 163, name: "Veer Singh", netid: "dvsingh2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 164, name: "Will Qualls", netid: "wqualls2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 165, name: "Yang Jialiangcheng", netid: "jy81", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 166, name: "Yiran Chen", netid: "yiran25", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 167, name: "Yuheng Guo", netid: "yuheng4", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 168, name: "Yung Man Yu", netid: "ymyu2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 169, name: "Yuqi Wen", netid: "yuqiwen3", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 170, name: "Zach Li", netid: "zichenl7", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 171, name: "Zach Olmsted", netid: "zvo2", events: 1, points: 0, delta: -3, gained: 0 },
  { rank: 172, name: "Zihao Chen", netid: "leochen4", events: 1, points: 0, delta: -3, gained: 0 },
];
